export enum Difficulty {
  Basic = "Base",
  Intermediate = "Intermedio",
  Advanced = "Avanzato"
}

export enum CardType {
  TrueFalse = "true_false",
  MultipleChoice = "multiple_choice",
  Basic = "basic"
}

export interface Flashcard {
  id: number;
  type: CardType;
  question: string;
  options?: string[]; // For Multiple Choice
  correctAnswer: string; // "True"/"False", the option text, or the full text answer
  userExplanation?: string; // Optional context generated by AI
}

export interface Settings {
  cardCount: number;
  difficulty: Difficulty;
  includeTrueFalse: boolean;
  includeMultipleChoice: boolean;
  includeBasic: boolean;
}

export interface GameState {
  score: number;
  answers: boolean[]; // true if correct, false if wrong
  currentCardIndex: number;
  isFinished: boolean;
}

export interface UserInput {
  text: string;
  fileName: string;
}
